### ISSUE TITLE
1.3.2. Interface de usuário (até 2,0 pontos)

### ISSUE THREAD

**Issue by Rizzi26** [Inteli-College/2024-1B-T08-EC06-G01#15]
[1,5 - 2,0]
A interface é bem projetada, intuitiva e facilita o controle eficaz e imediato do robô.

**Comment by laurapbueno** [comment]
- O operador deve ser capaz de controlar o robô utilizando uma interface de usuário simplificada, que pode ser um terminal básico ou uma interface gráfica simples, conforme a escolha da equipe.
